

[uic.name]
en= "University of Illinois at Chicago",
es= "La Universidad de Illinois en Chicago"

[uic.primaryContact]
name= "Stockton Mayer",
phone= "+1-312-996-6732",
email= "smayer75@uic.edu"

[uic.summary]
es= "El Departamento de Enfermedades Infecciosas de la Universidad de Illinois (UIC), Chicago facilita educación avanzada en temas relacionados con VIH.  Colaboramos con profesionales médicos en la provincia de La Romana para elaborar proyectos educativos enfocados en el manejo de pacientes infectados por el virus.",
en= "The Department of Infectious Diseases of the University of Illinois at Chicago (UIC) facilitates advanced education on topics related to HIV. We Collaborate with medical professionals in the province of La Romana to create educational projects that focus on the management of patients infected with HIV."

[uic.locations]
es= "UIC realiza proyectos en La Romana, Guaymate y sus alrededores."
en= "UIC has ongoing projects in La Romana, Guaymate, and the surrounding communities"

[uic.researchOngoing]
es= "Con el apoyo de Clínica de Familia en La Romana, La Universidad de Illinois investiga la circuncisión masculina en hombres heterosexuales como método de reducir el riesgo de infección por el VIH."
en= "With the assistance of the Clínica de Familia, UIC is investigating curcumscision of heterosexual males as a method of reducing the risk of HIV infection."

[uic.researchGoals]
es= "Las investigaciones enfocan en la aceptabilidad del procedimiento y la habilidad de introducir la circuncisión masculina en una sociedad no habituada al procedimiento."
en= "The investigations focus on the acceptability of the procedure and ability of introducing male circumscision in a society that is not accostomed to the procedure."


[t53w.name]
en= "The 53rd Week",
es= "La Semana 53"

[t53w.primaryContact]
name= "Lawrence Loh",
phone= "+1-647-281-5971",
email= "lloh@jhsph.edu"

[t53w.summary]
es= "The 53rd Week tiene el objetivo de mejorar el trabajo realizado por los interesados en los bateyes a través de fomentar la colaboración en la educación, la investigación y la promoción, con el objetivo de apuntar a aguas arriba, con una duración, impactos sostenibles a los sanitarios y sociales circunstancias dentro de los bateyes."
en= ""

[t53w.locations]
es= "The 53rd Week respeta la importancia de la autonomía local y trabaja en lo que sea bateyes son identificados por nuestro socio, el Hospital Buen Samaritano."
en= ""

[t53w.researchOngoing]
es= "Estamos llevando a cabo análisis cualitativos del impacto actual y el funcionamiento de equipos de voluntarios que visitan con el Hospital Buen Samartian, así como en desarrollo evaluaciones de las necesidades y perfiles de salud de varias comunidades de los bateyes. También estamos involucrados en la publicación sobre el tema más amplio del voluntariado de la salud mundial y teniendo en cuenta los problemas éticos en la educación y formación en el extranjero. "
en= ""

[t53w.researchGoals]
es= "El objetivo de nuestro trabajo es determinar los impactos de referencia que el voluntariado de corto plazo está teniendo en los bateyes de La Romana, identificar las mejoras potenciales, y ayudar con la implementación de modelos de colaboración y proyectos conjuntos a mejorar la salud y las condiciones sociales en los bateyes."
en= ""
